default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: pass21
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gethelp_development


test:
  <<: *default
  database: gethelp_test

